{
 "title": "TCC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pushgateway - Start Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "start{exported_job=\"turtlesim\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pushgateway - Collision Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "collision{exported_job=\"turtlesim\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pushgateway - Linear and Angular velocities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "angular_velocity", "legendFormat": "__auto" },
    { "expr": "linear_velocity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pushgateway - X and Y positions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "x_position", "legendFormat": "__auto" },
    { "expr": "y_position", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node_Exporter - Average Amount of CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node_Exporter - Mem Available [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}