global:
  scrape_interval: 1s
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "pushgateway"
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
